[Project]
Name = "RevanScript (RVS)"
Version = "1.0"

[Compiler]
Name0 = "gcc"
Name1 = "clang"
Name2 = "x86_64-w64-mingw32-gcc"

[Build]
SourceFiles = [
    "../src/main.c",
    "../src/rvsbuf.c",
    "../src/rvsctl.c",
    "../src/rvsexp.c",
    "../src/rvsflg.c",
    "../src/rvsio.c",
    "../src/rvslgc.c",
    "../src/rvsmem.c",
    "../src/rvsmth.c",
    "../src/rvsprs.c",
    "../src/rvsstd.c",
    "../src/rvstbl.c",
    "../src/rvskey.c",
    "../src/rvsarr.c",
    "../src/rvsmtx.c"
]
ObjectFiles = [
    "../objects/main.o",
    "../objects/rvsbuf.o",
    "../objects/rvsctl.o",
    "../objects/rvsexp.o",
    "../objects/rvsflg.o",
    "../objects/rvsio.o",
    "../objects/rvslgc.o",
    "../objects/rvsmem.o",
    "../objects/rvsmth.o",
    "../objects/rvsprs.o",
    "../objects/rvsstd.o",
    "../objects/rvstbl.o",
    "../objects/rvskey.o",
    "../objects/rvsarr.o",
    "../objects/rvsmtx.o"
]
Flags = [
    "-static",
    "-std=c99",
    "-O2"
]
LinuxOutputFile = "../bin/gcc/RevanScript"
WindowsOutputFile = "../bin/gcc/RevanScript.exe"
